name = "snippet-share"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "SNIPPETS", id = "0b29664744ba4bec832389d98fc13e30" }
]

[vars]
ALLOWED_ORIGINS = "http://localhost:3001,http://localhost:3000,https://snip.goodheart.tech"

[site]
bucket = "./dist" 