name = "wishlist"
main = "src/worker.ts"
compatibility_date = "2025-06-24" # always try to use TODAY's date when re-deploying to keep JavaScript runtime up to date
workers_dev = false #disables the public visibility of the worker

# DEFINE CUSTOM DOMAIN BELOW
routes = [
  { pattern = "snip.nonprofittools.org", custom_domain = true }
]

[vars]
PAGE_TITLE = "Good Heart Tech's Secure Snippet Sharing"
WELCOME_MESSAGE = "Note: For secure <i>password</i> sharing, we recommend <a href='https://push.goodheart.tech'>https://push.goodheart.tech</a>"
BACKGROUND_COLOR = "#091D20"
FONT_COLOR = "#FFFFFF"
ACCENT_COLOR = "#7189ff"

[[kv_namespaces]]
binding = "SNIPPETS"
id = "0b29664744ba4bec832389d98fc13e30"
